-- AlterTable
ALTER TABLE "Product" ADD COLUMN "createBy" TEXT;
ALTER TABLE "Product" ADD COLUMN "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Product" ADD COLUMN "isDeleted" BOOLEAN DEFAULT false;
ALTER TABLE "Product" ADD COLUMN "updateBy" TEXT;
ALTER TABLE "Product" ADD COLUMN "updatedAt" DATETIME;
